### ISSUE TITLE
Test use of '/user/:id'

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/angular-ngroute-lab#2]
Tests/Routes.spec.js:13-14 read:

```
it('should have the correct URL', function () {
            state = $route.routes['/user/:id'];
```

While this is correct, students may be inclined to define the route as '/user/:name' in config. After all the url reads `http://localhost:8080/#/user/liam`, where 'liam' is the first name. If they make the change, all 3 tests fail because the symbol `:id` is not defined (`:name` is). May be worth a note on the readme, and or update to test.

**Comment by onyoo** [comment]
Oh! Update: the readme _does_ say to define `:name` in the route, so I think the test must be updated ^^

**Comment by AnnJohn** [comment]
ahh thanks, will update.
